// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qslqwrvuubwbkbtkhgcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzbHF3cnZ1dWJ3YmtidGtoZ2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Nzg3NDIsImV4cCI6MjA2NjQ1NDc0Mn0.pLJHF0DWI3hzYFuf5OOZ6M_xIAcmdTcW1dCsDzoEEQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);